apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: NodePort
  ports:
    - name: keyclaok
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: keycloak
